### ISSUE TITLE
Can you update the binary of phantomjs?

### ISSUE THREAD

**Issue by alexyr** [iiLaurens/openshift-selenium-phantomjs#1]
Or at least show your changes in it's source code?

**Comment by alexyr** [comment]
I see, you used the current stable version 2.1?

**Comment by iiLaurens** [comment]
I stopped this project so I won't be making a new binary. However, you can build it yourself. The patch that I applied is rather simple and can be found here:
https://github.com/laurentj/ghostdriver/commit/e7bb101a8eb282ebf6e42ca79dcd25d544cfd35b

**Comment by alexyr** [comment]
Thanks! The change is not in the phantomjs binary, right?

**Comment by alexyr** [comment]
Found it, thanks a lot! Your solution saved me lots of work in my openshift project!
